Repository Sejong-GG/Sejong.GG, pull requests merged in 2021-07, with the labels that each got.

#3 feat : node.js 프로젝트 초기 설정 [#2]
  app.js
  package-lock.json
  package.json
  public/main.css
  routes/index.js
  schemas/index.js
  socket.js
  views/error.html
  views/main.html
Labels: 🍆 feature

#5 feat : layout.html 연결 [#4]
  views/layout.html
  views/main.html
Labels: 🍆 feature

#7 fix : axios 버전 변경[#6]
  package-lock.json
  package.json
Labels: 🔨 fix

#15 feat : op.gg 챔피언 팁 크롤링 [#8]
  crawl.js
  package-lock.json
  package.json
Labels: 🍆 feature

#17 feat : 크롤링 데이터를 몽고DB에 삽입
  crawl.js
  routes/index.js
  schemas/champion.js
Labels: 🍆 feature

#18 wired-element 설정, [lobby,room] 페이지 추가
  docker-compose.yml
  package-lock.json
  package.json
  public/main.css
  routes/index.js
  views/layout.html
  views/lobby.html
  views/room.html
Labels: 🍆 feature, 🍌 chore

#20 chore : wired-elements 및 routes설정 변경 [#9]
  views/layout.html
  views/login.html
Labels: 🍌 chore

#21 feat : 랜덤 닉네임 짓기 [#10]
  public/main.css
  views/login.html
Labels: 🍆 feature, 🍌 chore

#29 fix : view 화면 오류 수정 [#23]
  public/main.css
  views/lobby.html
  views/login.html
  views/room.html
Labels: 🔨 fix

#34 feat : 싱글 방 입장시 화면 구성
  public/main.css
  routes/index.js
  views/single.html
Labels: 🍆 feature, 🍌 chore

#37 feat : login페이지 사용자 이름 세션에 저장 [#11, #19, #35]
  app.js
  package-lock.json
  package.json
  routes/index.js
  views/lobby.html
  views/login.html
Labels: 🍆 feature

#32 [lobby, room]페이지 가운데 정렬
  public/main.css
  views/layout.html
  views/lobby.html
  views/main.html
  views/room.html
Labels: 🔨 fix

#39 fix : 싱글 게임 화면 오류 수정
  public/main.css
  views/single.html
Labels: 🔨 fix

#43 feat : 로딩 화면 구성
  public/main.css
  routes/index.js
  views/loading.html
Labels: 🍆 feature, 🍌 chore

#46 fix : 싱글방 힌트 박스 수정 방지 [#45]
  public/main.css
  views/single.html
Labels: 🔨 fix

#44 feat : rank 페이지 생성 [#41]
  public/main.css
  routes/index.js
  views/rank.html
Labels: 🍆 feature

#49 feat : chat,room,rank 스키마 생성 [#14]
  schemas/chat.js
  schemas/rank.js
  schemas/room.js
Labels: 🍆 feature

#48 feat : 싱글방 화면에 문제 구성, 확인 버튼 기능
  views/lobby.html
  views/single.html
Labels: 🍆 feature

#42 feat : 싱글방 문제세트를 싱글로 전송 [#27]
  routes/index.js
  socket.js
Labels: 🍆 feature

#51 fix : 요청받은 수정사항 수정 [#27]
  socket.js
Labels: 🍆 feature

#55 feat : 로딩 화면 view 기능 추가
  public/main.css
  views/loading.html
  views/single.html
Labels: 🍆 feature

#58 feat : 채팅방 페이지 생성
  public/main.css
  routes/index.js
  views/chat.html
  views/lobby.html
Labels: 🍆 feature

#59 feat : 욕설, 비속어, 챔피언 이름 필터링 [#56]
  crawl.js
  routes/index.js
Labels: 🍆 feature

#60 fix : merge conflict 수정
  socket.js
  views/single.html
Labels: 🔨 fix

#65 style : 로비에 있는 userName 삭제
  views/lobby.html
Labels: 🔨 fix

#69 style : 싱글 화면 view 스타일 추가
  public/main.css
  views/single.html
Labels: 🌷 design, 🔨 fix

#68 feat : 서버에서 정답 비교하기 구현 [#66]
  socket.js
Labels: 🍆 feature

#76 feat : rank top10 값 프론트에 전송
  routes/index.js
  schemas/rank.js
Labels: 🍆 feature

#77 refactor : response 이벤트 이름 수정 [#75]
  socket.js
Labels: 🥚 refactor

#74 style : rank 페이지 테이블 수정
  public/main.css
  views/rank.html
Labels: 🌷 design, 🔨 fix

#81 style : 채팅방 스타일 수정 [#80]
  public/main.css
  views/chat.html
Labels: 🌷 design, 🔨 fix

#83 refactor : 닉네임을 세션에 저장하는 방식 변경
  routes/index.js
  views/login.html
Labels: 🥚 refactor

#85 refactor : href 경로 변경, html 변경
  routes/index.js
  schemas/chat.js
  schemas/index.js
  schemas/rank.js
  views/chat.html
  views/loading.html
  views/lobby.html
  views/login.html
  views/rank.html
  views/room.html
  views/single.html
Labels: 🍌 chore

#84 refactor : 세션에 닉네임이 없으면 login으로 리다이렉트
  routes/index.js
Labels: 🥚 refactor

#86 feat : 테스트 데이터 받아서 뷰에 render [#79]
  routes/index.js
  views/rank.html
Labels: 🍆 feature

#87 feat : 싱글방 세션에서 카운트(점수,시간) 저장
  socket.js
  views/login.html
  views/single.html
Labels: 🍆 feature, 🍌 chore

#88 style : 로비 화면 수정 [#82]
  public/main.css
  views/lobby.html
Labels: 🌷 design, 🔨 fix

#95 refactor : 전체 view 높이 수정 [#93]
  public/main.css
  views/chat.html
Labels: 🥚 refactor

#96 fix : rank 페이지에서 userName 노출 조건 추가 [#91]
  views/rank.html
Labels: 🔨 fix

#105 feat : 로비에 /rank 이동 버튼 추가 [#101]
  public/main.css
  views/lobby.html
Labels: 🍆 feature

#103 feat : 로딩 화면 연결 [#99]
  views/lobby.html
Labels: 🍆 feature

#106 feat : 인덱스에 맞는 한글이름을 받아오도록 설정 [#98]
  routes/index.js
  socket.js
  util/champ.js
  util/crawler.js
  util/word.js
Labels: 🍆 feature

#109 feat : 크롤링한 데이터 필터링 [#102]
  util/champ.js
  util/crawler.js
  util/word.js
Labels: 🍆 feature

#110 fix : 싱글 게임 인풋 값 오류 수정 [#108]
  views/single.html
Labels: 🔨 fix

#111 feat : 챔피언, 문제 중복 해결
  socket.js
  views/rank.html
  views/single.html
Labels: 🍆 feature, 🍌 chore, 🔨 fix

#113 refactor : 싱글 게임 코드 변경 [#112]
  views/single.html
Labels: 🥚 refactor

#114 refactor : ip주소 .env로 변경, 정렬 오류 수정
  routes/index.js
  schemas/rank.js
  views/chat.html
  views/single.html
Labels: 🥚 refactor

#116 feat : heroku 배포를 위한 db 설정 변경 [#115]
  schemas/index.js
Labels: 🍆 feature

#117 feat : 배포를 위한 npm 스크립트 변경
  package.json
Labels: 🍆 feature

#118 fix : socket 통신 url 변경
  views/chat.html
  views/single.html
Labels: 🔨 fix

#120 fix : 소켓 안되는 오류 수정
  app.js
  views/single.html
Labels: 🔨 fix

#121 fix : single페이지에서 alert 대체, 맞춘개수 문구 추가
  public/main.css
  views/lobby.html
  views/single.html
Labels: 🍌 chore, 🔨 fix

#122 fix : single 소켓 통신안되는 오류 수정
  views/single.html
Labels: 🔨 fix

#123 feat : OG 태그 설정
  views/layout.html
Labels: 🍆 feature

#124 feat : og title, description 추가
  public/img.png
  views/layout.html
Labels: 🍆 feature

#125 DOC : Update Readme.md
  README.md
  public/chat.gif
  public/play.gif
Labels: :memo: docs

#132 feat : single 페이지 현재까지 푼 문제 수 추가 [#126]
  views/single.html
Labels: 🍆 feature

#133 feat : 채팅방에 현재 접속자 수 추가 [#128]
  public/main.css
  socket.js
  views/chat.html
Labels: 🍆 feature, 🔨 fix
